name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          yarn
          yarn test
        env:
          CI: true
  codecov:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: yarn install and build test coverage
        run: |
          yarn
          yarn test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v5
  # codeclimate:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@master
  #     - name: yarn install
  #       run: yarn
  #     - name: Code Climate
  #       uses: paambaati/codeclimate-action@v5.0.0
  #       env:
  #         CC_TEST_REPORTER_ID: 0821c701bb20ce2afc198c727f4a8aefaecc87bf6af23f1aafd2e0fe1b09d8bf
  #       with:
  #         coverageCommand: yarn test --coverage
  #         debug: true
